name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Upload to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli upload ./ --repo-type=space --repo-id vionnagau/diabetes-project-new --token $HF_TOKEN
